networks:
  gitea:
    external: false

services:
  git:
    image: docker.gitea.com/gitea:1.24.6
    container_name: gitea.core 
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASSWD}
      - GITEA__server__ROOT_URL=https://git.pngwna.net/
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea.db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
      - TZ=Asia/Seoul
    networks:
      - gitea
    command: ["postgres", "-c", "unix_socket_directories="]
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data