#cloud-config
  hostname: ${hostname}
  timezone: Asia/Seoul
  users:
    - default
    - name: celestrial
      groups:
        - sudo
      shell: /bin/bash
      ssh_authorized_keys:
        - ${ssh_pubkey}
      sudo: ALL=(ALL) NOPASSWD:ALL
  package_update: true
  packages:
    - qemu-guest-agent
    - apt-transport-https 
    - ca-certificates 
    - containerd
    - curl
    - gnupg
  write_files:
    - path: /etc/kubernetes/kubeadm.yaml
      content: |
        ${indent(8, file("cloud-init/kubernetes/kubeadm.yaml"))}
    - path: /etc/containerd/config.toml
      content: |
        ${indent(8, file("cloud-init/containerd/config.toml"))}
  runcmd:
    - systemctl enable --now qemu-guest-agent
    - systemctl enable --now containerd
    - sysctl -w net.ipv4.ip_forward=1
    - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - apt-get update
    - apt-get install -y kubelet kubeadm kubectl
    - apt-mark hold kubelet kubeadm kubectl
    - kubeadm config images pull --kubernetes-version v1.34.0
    - kubeadm init --config /etc/kubernetes/kubeadm.yaml
    - echo "done" > /tmp/cloud-config.done