#cloud-config
  hostname: ${hostname}
  timezone: Asia/Seoul
  ssh_pwauth: true
  users:
    - default
    - name: celestrial
      groups:
        - sudo
      shell: /bin/bash
      lock_passwd: false
      passwd: ${vm_password}
      ssh_authorized_keys:
        - ${ssh_pubkey}
      sudo: ALL=(ALL) NOPASSWD:ALL
  package_update: true
  packages:
    - qemu-guest-agent
    - apt-transport-https 
    - ca-certificates 
    - containerd
    - curl
    - gnupg
  runcmd:
    - systemctl enable --now qemu-guest-agent
    - systemctl enable --now containerd
    - sysctl -w net.ipv4.ip_forward=1
    - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - apt-get update
    - apt-get install -y kubelet kubeadm kubectl
    - apt-mark hold kubelet kubeadm kubectl
    - echo "done" > /tmp/cloud-config.done